### ISSUE TITLE
shp download includes multiple shapefiles - sometimes

### ISSUE THREAD

**Issue by courtneycl** [koopjs/koop-opendata#11]
STR
1. download: http://koop.dc.esri.com/openData/umbrella/keyword/parcel/place/united+states.zip
2. open, observe: 
![screen shot 2015-06-22 at 5 30 22 pm](https://cloud.githubusercontent.com/assets/3474250/8293579/5b1ab288-1904-11e5-944e-20724c916500.png)

We see three copies of the same shapefile with three different names. Expected to just see one.

**Comment by chelm** [comment]
@dmfenton it looks like koop's core exporters are exporting everything inside the dir and not respecting the passed in key. Not sure why, but you could add a subdir to prevent files from ever being written to the same dir.

To do this add the "key" var to the dir here: https://github.com/koopjs/koop-opendata/blob/master/controller/index.js#L78

**Comment by dmfenton** [comment]
@chelm That would probably help, but koop should also be cleaning up these temp files too.

**Comment by dmfenton** [comment]
actually that didnt work
