### ISSUE TITLE
geojson and csv are limited to 100 features 

### ISSUE THREAD

**Issue by courtneycl** [koopjs/koop-opendata#14]
http://koop.dc.esri.com/openData/umbrella/q/address+points/place/united+states.geojson and http://koop.dc.esri.com/openData/umbrella/q/address+points/place/united+states.csv only return 100 features, but there are 217 features returned with this query - http://koop.dc.esri.com/openData/umbrella/q/address+points/place/united+states/featureserver/0/query

@dmfenton

**Comment by dmfenton** [comment]
Resolved in 52eae99cc46c7043b2c6e989638a85878232b0ea
