### ISSUE TITLE
geojson not getting dropped properly

### ISSUE THREAD

**Issue by courtneycl** [koopjs/koop-opendata#15]
`group` property appears in the basic call, but does not appear in geojson. 

http://koop.dc.esri.com/openData/umbrella/q/address+points/place/united+states has `group`
http://koop.dc.esri.com/openData/umbrella/q/address+points/place/united+states.geojson does not. 

@dmfenton

**Comment by dmfenton** [comment]
Resolved in 52eae99cc46c7043b2c6e989638a85878232b0ea
