### ISSUE TITLE
1.0.0 release does not match npm release

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop-opendata#8]
https://github.com/koopjs/koop-opendata/releases/tag/1.0.0 does not match 1.0.0 on https://www.npmjs.com/package/koop-opendata.

We need to either unpublish what's on NPM and redo the publish step to match what's on github, or delete the release on github and bump the version.

@dmfenton

**Comment by ungoldman** [comment]
It would also be best to have a change log in there before making the release official.

**Comment by dmfenton** [comment]
Cool, thanks for keeping me honest. I'll clean it up today.

**Comment by ungoldman** [comment]
@dmfenton is it alright if I fix the tags & releases for this repo? I want to make them consistent with the rest of the koopjs repos.

**Comment by dmfenton** [comment]
Sure

On Tue, Jun 30, 2015 at 4:15 PM -0700, "Nate Goldman" <notifications@github.com<mailto:notifications@github.com>> wrote:

@dmfentonhttps://github.com/dmfenton is it alright if I fix the tags & releases for this repo? I want to make them consistent with the rest of the koopjs repos.

**Comment by dmfenton** [comment]
I thought I fixed the offending release on NPM by doing unpublish.

**Comment by ungoldman** [comment]
nope, it's still there. will fix github releases for now.

**Comment by ungoldman** [comment]
actually it's not, sorry, was looking at `time` instead of `versions` from `npm info koop-opendata`

```
  versions: [ '1.0.1', '1.1.0', '1.1.1', '1.1.3', '1.1.4' ],
  maintainers: 'dmfenton <dfenton@esri.com>',
  time:
   { modified: '2015-07-01T20:57:44.900Z',
     created: '2015-06-15T16:51:36.668Z',
     '1.0.0': '2015-06-15T16:51:36.668Z',
     '1.0.1': '2015-06-25T12:36:12.389Z',
     '1.1.0': '2015-06-30T20:13:53.878Z',
     '1.1.1': '2015-07-01T14:58:33.995Z',
     '1.1.2': '2015-07-01T18:43:15.836Z',
     '1.1.3': '2015-07-01T20:31:43.941Z',
     '1.1.4': '2015-07-01T20:57:44.900Z' }
```

will remove 1.0.0 and 1.1.2 from releases. should be fine now.

**Comment by ungoldman** [comment]
In the future, keeping version commits separate makes tracking releases and going through history a whole lot easier for users and maintainers. For example https://github.com/ngoldman/module-init/commit/5c0662afae2b408093c5b42a1d1322fed6a059ad is easy to spot and understand when scanning through git history (https://github.com/ngoldman/module-init/commits/master).

**Comment by dmfenton** [comment]
Cool, will do so in the future. Thanks for the help.
